### ISSUE TITLE
react-native link adds com.Traviskn.RNUUIDGeneratorPackage

### ISSUE THREAD

**Issue by ghost** [Traviskn/react-native-uuid-generator#10]
`error: cannot find symbol

import com.Traviskn.RNUUIDGeneratorPackage;

  symbol:   class RNUUIDGeneratorPackage

  location: package com.Traviskn`

Works after manually change MainApplication.java content to

import io.github.traviskn.rnuuidgenerator.RNUUIDGeneratorPackage;

**Comment by Traviskn** [comment]
Thanks for letting me know, I'd forgotten to update the AndroidManifest.xml with the correct package name.  Should now be fixed in the latest version
