### ISSUE TITLE
Why the process is async?

### ISSUE THREAD

**Issue by mgtitimoli** [Traviskn/react-native-uuid-generator#12]
Hey @Traviskn,

Before going further I want to thank you for having published this, thanks!

I was just wondering why the necessity of going async, can you give me an insight on the decisions around this?

Thanks again!

**Comment by Traviskn** [comment]
In react native, JS and native code communicate over an asynchronous bridge. This library's uuid generator being async is because of the architectural restrictions of react native itself, I'm not sure it is possible to synchronously call native code from JS.
