### ISSUE TITLE
life time for the UUID generator?

### ISSUE THREAD

**Issue by saikiranoptisol** [Traviskn/react-native-uuid-generator#16]
Before using this library i just want to know will this uuid be generated everytime i open my app or else. it will generated for the first time when the app is installed and will be removed after uninstalling the app.

**Comment by mfachmirizal** [comment]
I'm not the maintainer but I will try to answer your question..
I think this lib will generate the id everytime when the function is called.. so you must check before, if your device is not already have this uuid, then generate. Else use the generated id before (from asyncstorage or another storage)..
CMIIW
