### ISSUE TITLE
React-Native 0.40 , #import <React/RCTDefines.h> file not found

### ISSUE THREAD

**Issue by Mactub07** [Traviskn/react-native-uuid-generator#4]
it happens after update

**Comment by Traviskn** [comment]
This should now be fixed as of the latest version, 2.0.0

**Comment by Mactub07** [comment]
did you release one ? I mean v 2.0.0

**Comment by Traviskn** [comment]
Yes I just published v 2.0.0 last night to npm: https://www.npmjs.com/package/react-native-uuid-generator

**Comment by Mactub07** [comment]
Thanks a lot :) now it works

**Comment by Traviskn** [comment]
Great, sounds good!
