### ISSUE TITLE
error: RNUUIDGeneratorPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by ghost** [Traviskn/react-native-uuid-generator#8]
I am using
-"react": "16.0.0-alpha.12",
-"react-native": "^0.46.4",
-"react-native-uuid-generator": "^3.0.2",

**Comment by Traviskn** [comment]
This package's peer dependency on react-native is a version greater than 0.47, unfortunately 0.46 is not supported on the latest version
